"""
Processing orchestrator
Responsible for coordinating pipeline execution and Task state management
"""

import logging
import time
import sys
from typing import Dict, Any, List, Optional, Callable
from pathlib import Path
from sqlalchemy.orm import Session

from backend.models.task import Task, TaskStatus, TaskType
from backend.repositories.task_repository import TaskRepository
from backend.services.config_manager import ProjectConfigManager, ProcessingStep
# from backend.services.pipeline_adapter import PipelineAdapter  # Temporarily commented out, file does not exist
from backend.core.config import get_project_root

logger = logging.getLogger(__name__)

# Import pipeline steps

try:
    from backend.pipeline.step1_outline import run_step1_outline
    from backend.pipeline.step2_timeline import run_step2_timeline
    from backend.pipeline.step3_scoring import run_step3_scoring
    from backend.pipeline.step4_title import run_step4_title
    from backend.pipeline.step5_clustering import run_step5_clustering
    from backend.pipeline.step6_video import run_step6_video
    logger.info("Pipeline modules imported successfully")
except ImportError as e:
    logger.warning(f"Unable to import pipeline modules: {e}")
    # Define placeholder functions
    def run_step1_outline(**kwargs): 
        logger.warning("Pipeline modules not properly imported, using placeholder function")
        # Generate mock output
        srt_path = kwargs.get('srt_path')
        output_path = kwargs.get('output_path')
        if output_path:
            import json
            from pathlib import Path
            # Ensure output_path is a Path object
            if isinstance(output_path, str):
                output_path = Path(output_path)
            output_path.parent.mkdir(parents=True, exist_ok=True)
            mock_output = {
                "outlines": [
                    {"topic": "Test topic 1", "start_time": "00:00:00", "end_time": "00:00:05", "content": "Test content 1"},
                    {"topic": "Test topic 2", "start_time": "00:00:05", "end_time": "00:00:10", "content": "Test content 2"}
                ],
                "status": "completed",
                "message": "Mock output generated by placeholder function"
            }
            with open(output_path, 'w', encoding='utf-8') as f:
                json.dump(mock_output, f, ensure_ascii=False, indent=2)
        return {"status": "skipped", "message": "Pipeline modules not properly imported"}
    
    def run_step2_timeline(**kwargs): 
        logger.warning("Pipeline modules not properly imported, using placeholder function")
        # Generate mock output
        output_path = kwargs.get('output_path')
        if output_path:
            import json
            from pathlib import Path
            # Ensure output_path is a Path object
            if isinstance(output_path, str):
                output_path = Path(output_path)
            output_path.parent.mkdir(parents=True, exist_ok=True)
            mock_output = {
                "timeline": [
                    {"time": "00:00:00", "event": "Start"},
                    {"time": "00:00:05", "event": "Topic 1"},
                    {"time": "00:00:10", "event": "Topic 2"}
                ],
                "status": "completed",
                "message": "Mock output generated by placeholder function"
            }
            with open(output_path, 'w', encoding='utf-8') as f:
                json.dump(mock_output, f, ensure_ascii=False, indent=2)
        return {"status": "skipped", "message": "Pipeline modules not properly imported"}
    
    def run_step3_scoring(**kwargs): 
        logger.warning("Pipeline modules not properly imported, using placeholder function")
        # Generate mock output
        output_path = kwargs.get('output_path')
        if output_path:
            import json
            from pathlib import Path
            # Ensure output_path is a Path object
            if isinstance(output_path, str):
                output_path = Path(output_path)
            output_path.parent.mkdir(parents=True, exist_ok=True)
            mock_output = {
                "scored_clips": [
                    {"clip_id": "1", "score": 0.8, "content": "High score content 1"},
                    {"clip_id": "2", "score": 0.7, "content": "High score content 2"}
                ],
                "status": "completed",
                "message": "Mock output generated by placeholder function"
            }
            with open(output_path, 'w', encoding='utf-8') as f:
                json.dump(mock_output, f, ensure_ascii=False, indent=2)
        return {"status": "skipped", "message": "Pipeline modules not properly imported"}
    
    def run_step4_title(**kwargs): 
        logger.warning("Pipeline modules not properly imported, using placeholder function")
        # Generate mock output
        output_path = kwargs.get('output_path')
        if output_path:
            import json
            from pathlib import Path
            # Ensure output_path is a Path object
            if isinstance(output_path, str):
                output_path = Path(output_path)
            output_path.parent.mkdir(parents=True, exist_ok=True)
            mock_output = {
                "titles": [
                    {"clip_id": "1", "title": "Test title 1"},
                    {"clip_id": "2", "title": "Test title 2"}
                ],
                "status": "completed",
                "message": "Mock output generated by placeholder function"
            }
            with open(output_path, 'w', encoding='utf-8') as f:
                json.dump(mock_output, f, ensure_ascii=False, indent=2)
        return {"status": "skipped", "message": "Pipeline modules not properly imported"}
    
    def run_step5_clustering(**kwargs): 
        logger.warning("Pipeline modules not properly imported, using placeholder function")
        # Generate mock output
        output_path = kwargs.get('output_path')
        if output_path:
            import json
            from pathlib import Path
            # Ensure output_path is a Path object
            if isinstance(output_path, str):
                output_path = Path(output_path)
            output_path.parent.mkdir(parents=True, exist_ok=True)
            mock_output = {
                "collections": [
                    {"collection_id": "1", "title": "Test collection 1", "clips": ["1", "2"]},
                    {"collection_id": "2", "title": "Test collection 2", "clips": ["3", "4"]}
                ],
                "status": "completed",
                "message": "Mock output generated by placeholder function"
            }
            with open(output_path, 'w', encoding='utf-8') as f:
                json.dump(mock_output, f, ensure_ascii=False, indent=2)
        return {"status": "skipped", "message": "Pipeline modules not properly imported"}
    
    def run_step6_video(**kwargs): 
        logger.warning("Pipeline modules not properly imported, using placeholder function")
        # Generate mock output
        output_path = kwargs.get('output_path')
        if output_path:
            import json
            from pathlib import Path
            # Ensure output_path is a Path object
            if isinstance(output_path, str):
                output_path = Path(output_path)
            output_path.parent.mkdir(parents=True, exist_ok=True)
            mock_output = {
                "videos": [
                    {"clip_id": "1", "video_path": "output/clip_1.mp4"},
                    {"clip_id": "2", "video_path": "output/clip_2.mp4"}
                ],
                "status": "completed",
                "message": "Mock output generated by placeholder function"
            }
            with open(output_path, 'w', encoding='utf-8') as f:
                json.dump(mock_output, f, ensure_ascii=False, indent=2)
        return {"status": "skipped", "message": "Pipeline modules not properly imported"}


class ProcessingOrchestrator:
    """Processing orchestrator, responsible for coordinating pipeline execution and Task state management"""
    
    def __init__(self, project_id: str, task_id: str, db: Session):
        self.project_id = project_id
        self.task_id = task_id
        self.db = db
        
        # Initialize components
        self.config_manager = ProjectConfigManager(project_id)
        # self.adapter = PipelineAdapter(db, task_id, project_id)  # Temporarily commented out, file does not exist
        self.task_repo = TaskRepository(db)
        
        # Step mapping
        self.step_functions = {
            ProcessingStep.STEP1_OUTLINE: run_step1_outline,
            ProcessingStep.STEP2_TIMELINE: run_step2_timeline,
            ProcessingStep.STEP3_SCORING: run_step3_scoring,
            ProcessingStep.STEP4_TITLE: run_step4_title,
            ProcessingStep.STEP5_CLUSTERING: run_step5_clustering,
            ProcessingStep.STEP6_VIDEO: run_step6_video
        }
        
        # Step adapter mapping - temporarily disabled
        self.step_adapters = {
            # ProcessingStep.STEP1_OUTLINE: self.adapter.adapt_step1_outline,
            # ProcessingStep.STEP2_TIMELINE: self.adapter.adapt_step2_timeline,
            # ProcessingStep.STEP3_SCORING: self.adapter.adapt_step3_scoring,
            # ProcessingStep.STEP4_TITLE: self.adapter.adapt_step4_title,
            # ProcessingStep.STEP5_CLUSTERING: self.adapter.adapt_step5_clustering,
            # ProcessingStep.STEP6_VIDEO: self.adapter.adapt_step6_video
        }
        
        # Step status management
        self.step_status = {}
        self.step_timings = {}
        self.step_results = {}
    
    def execute_step(self, step: ProcessingStep, **kwargs) -> Dict[str, Any]:
        """
        Execute a single step
        
        Args:
            step: Processing step
            **kwargs: Step-specific parameters
            
        Returns:
            Step execution result
        """
        step_name = step.value
        logger.info(f"Starting step execution: {step_name}")
        
        # Update step status to running
        self._update_step_status(step, "running")
        
        try:
            # Get step number
            step_number = self._get_step_number(step)
            
            # Update task status to running
            self._update_task_status(TaskStatus.RUNNING, progress=self._get_step_progress(step), current_step=step_number)
            
            # Get step function and adapter
            step_func = self.step_functions[step]
            step_adapter = self.step_adapters[step]
            
            # Prepare step environment
            self.adapter.prepare_step_environment(step_name)
            
            # Execute step (using high-precision timer)
            start_time = time.perf_counter()
            
            if step == ProcessingStep.STEP1_OUTLINE:
                # Step1 needs SRT file path
                srt_path = kwargs.get('srt_path')
                if not srt_path:
                    raise ValueError("Step1 requires SRT file path")
                
                adapted_params = step_adapter(srt_path)
            else:
                # Other steps use output from previous step
                adapted_params = step_adapter()
            
            # Execute step function
            result = step_func(**adapted_params)
            
            execution_time = time.perf_counter() - start_time
            logger.info(f"Step {step_name} execution completed, elapsed time: {execution_time:.4f}s")
            
            # Record step execution info
            self.step_timings[step_name] = {
                "start_time": start_time,
                "end_time": time.perf_counter(),
                "execution_time": execution_time
            }
            
            # Save result to database
            self._save_step_result(step, result)
            
            # Update step status to completed
            self._update_step_status(step, "completed", execution_time=execution_time)
            
            # Update task progress
            self._update_task_status(TaskStatus.RUNNING, progress=self._get_step_progress(step), current_step=step_number)
            
            return {
                "step": step_name,
                "status": "completed",
                "execution_time": execution_time,
                "result": result
            }
            
        except Exception as e:
            execution_time = time.perf_counter() - start_time if 'start_time' in locals() else 0
            logger.error(f"Step {step_name} execution failed: {e}")
            
            # Update step status to failed
            self._update_step_status(step, "failed", execution_time=execution_time, error=str(e))
            
            self._update_task_status(TaskStatus.FAILED, error_message=str(e))
            raise
    
    def execute_pipeline(self, srt_path: Path, steps_to_execute: Optional[List[ProcessingStep]] = None) -> Dict[str, Any]:
        """
        Execute pipeline (supports executing subset of steps on demand)
        
        Args:
            srt_path: SRT file path
            steps_to_execute: List of steps to execute, None means execute full pipeline
            
        Returns:
            Pipeline execution result
        """
        if steps_to_execute is None:
            # Execute full pipeline
            steps_to_execute = [
                ProcessingStep.STEP1_OUTLINE,
                ProcessingStep.STEP2_TIMELINE,
                ProcessingStep.STEP3_SCORING,
                ProcessingStep.STEP4_TITLE,
                ProcessingStep.STEP5_CLUSTERING,
                ProcessingStep.STEP6_VIDEO
            ]
            logger.info(f"Starting full pipeline execution for project {self.project_id}")
        else:
            logger.info(f"Starting subset pipeline execution for project {self.project_id}: {[step.value for step in steps_to_execute]}")
        
        # Validate prerequisites
        errors = self.adapter.validate_pipeline_prerequisites()
        if errors:
            error_msg = "; ".join(errors)
            self._update_task_status(TaskStatus.FAILED, error_message=error_msg)
            raise ValueError(f"Pipeline prerequisite validation failed: {error_msg}")
        
        # Validate step dependencies
        self._validate_step_dependencies(steps_to_execute)
        
        # Update task status to running
        self._update_task_status(TaskStatus.RUNNING, progress=0)
        
        results = {}
        total_steps = len(steps_to_execute)
        
        try:
            for i, step in enumerate(steps_to_execute):
                step_number = self._get_step_number(step)
                logger.info(f"Executing step {i+1}/{total_steps}: {step.value}")
                
                if step == ProcessingStep.STEP1_OUTLINE:
                    step_result = self.execute_step(step, srt_path=srt_path)
                else:
                    step_result = self.execute_step(step)
                
                results[step.value] = step_result
                
                # Update overall progress
                progress = ((i + 1) / total_steps) * 100
                self._update_task_status(TaskStatus.RUNNING, progress=progress, current_step=step_number)
            
            # Pipeline execution completed, save data to database
            self._save_pipeline_results_to_database(results)
            
            # Update task status to completed
            self._update_task_status(TaskStatus.COMPLETED, progress=100)
            
            logger.info(f"Project {self.project_id} pipeline execution completed")
            return {
                "status": "completed",
                "project_id": self.project_id,
                "task_id": self.task_id,
                "results": results,
                "executed_steps": [step.value for step in steps_to_execute]
            }
            
        except Exception as e:
            logger.error(f"Pipeline execution failed: {e}")
            self._update_task_status(TaskStatus.FAILED, error_message=str(e))
            raise
    
    def _update_step_status(self, step: ProcessingStep, status: str, execution_time: Optional[float] = None, 
                           error: Optional[str] = None):
        """Update step status"""
        step_name = step.value
        self.step_status[step_name] = {
            "status": status,
            "timestamp": time.time(),
            "execution_time": execution_time,
            "error": error
        }
        logger.debug(f"Step {step_name} status updated: {status}")
    
    def _update_task_status(self, status: TaskStatus, progress: Optional[float] = None, 
                           error_message: Optional[str] = None, result: Optional[Dict] = None,
                           current_step: Optional[int] = None):
        """Update task status"""
        # Use TaskRepository's specialized methods
        if progress is not None:
            self.task_repo.update_task_progress(self.task_id, progress)
        
        if error_message is not None:
            self.task_repo.update_task_error(self.task_id, error_message)
        
        if result is not None:
            self.task_repo.update_task_result(self.task_id, result)
        
        # Update status
        self.task_repo.update_task_status(self.task_id, status)
        
        # Update project status
        if current_step is not None:
            self._update_project_status(current_step, progress)
        
        logger.info(f"Task {self.task_id} status updated to: {status.value}, progress: {progress}%, step: {current_step}")
        
        # Send real-time progress update via WebSocket
        self._send_realtime_progress_update(status, progress, error_message, current_step)
    
    def _update_project_status(self, current_step: int, progress: Optional[float] = None):
        """Update project status"""
        try:
            from ..services.project_service import ProjectService
            from ..core.database import SessionLocal
            
            db = SessionLocal()
            try:
                project_service = ProjectService(db)
                project = project_service.get(self.project_id)
                if project:
                    # Update project status
                    update_data = {
                        "current_step": current_step,
                        "total_steps": 6,
                        "status": "processing" if current_step < 6 else "completed"
                    }
                    if progress is not None:
                        update_data["progress"] = progress
                    
                    project_service.update(self.project_id, **update_data)
                    db.commit()
                    logger.info(f"Project {self.project_id} status updated: step {current_step}/6, progress {progress}%")
                else:
                    logger.warning(f"Project {self.project_id} does not exist")
            finally:
                db.close()
        except Exception as e:
            logger.error(f"Failed to update project status: {e}")
    
    def _send_realtime_progress_update(self, status: TaskStatus, progress: Optional[float] = None, 
                                     error_message: Optional[str] = None, current_step: Optional[int] = None):
        """Send real-time progress update to frontend - integrated with snapshot publishing"""
        try:
            import asyncio
            import json
            from ..services.websocket_notification_service import WebSocketNotificationService
            from ..services.progress_snapshot_service import snapshot_service
            
            # Get current step info
            if current_step is None:
                current_step = 0
                step_name = "Initializing..."
                
                # Infer current step from progress
                if progress is not None:
                    if progress <= 10:
                        current_step = 1
                        step_name = "Outline extraction"
                    elif progress <= 30:
                        current_step = 2
                        step_name = "Timeline positioning"
                    elif progress <= 50:
                        current_step = 3
                        step_name = "Content scoring"
                    elif progress <= 70:
                        current_step = 4
                        step_name = "Title generation"
                    elif progress <= 85:
                        current_step = 5
                        step_name = "Topic clustering"
                    elif progress <= 95:
                        current_step = 6
                        step_name = "Video cutting"
                    else:
                        current_step = 6
                        step_name = "Processing complete"
            else:
                # Get step name from step number
                step_name_map = {
                    1: "Outline extraction",
                    2: "Timeline positioning", 
                    3: "Content scoring",
                    4: "Title generation",
                    5: "Topic clustering",
                    6: "Video cutting"
                }
                step_name = step_name_map.get(current_step, "Processing...")
            
            # Build progress message
            progress_message = f"Executing {step_name}..."
            if error_message:
                progress_message = f"Processing failed: {error_message}"
            elif status == TaskStatus.COMPLETED:
                progress_message = "Processing complete"
            
            # Build rich message payload
            payload = {
                "type": "task_progress_update",
                "task_id": self.task_id,
                "project_id": self.project_id,
                "status": status.value,
                "progress": progress or 0,
                "current_step": current_step,
                "total_steps": 6,
                "step_name": step_name,
                "phase": step_name,
                "message": progress_message,
                "timestamp": time.time()
            }
            
            # Send WebSocket notification and snapshot synchronously
            def send_notification():
                try:
                    # Try to get existing event loop
                    loop = asyncio.get_event_loop()
                    if loop.is_running():
                        # If event loop is running, use thread pool
                        import concurrent.futures
                        with concurrent.futures.ThreadPoolExecutor() as executor:
                            future = executor.submit(
                                asyncio.run,
                                self._async_send_progress_update(payload)
                            )
                            future.result(timeout=5)  # 5 second timeout
                    else:
                        # If event loop is not running, run directly
                        loop.run_until_complete(
                            self._async_send_progress_update(payload)
                        )
                except Exception as e:
                    logger.error(f"Failed to send WebSocket notification: {e}")
            
            # Send notification in background thread
            import threading
            thread = threading.Thread(target=send_notification)
            thread.daemon = True
            thread.start()
            
            logger.debug(f"Real-time progress update sent: {self.project_id} - {progress}% - {step_name}")
            
        except Exception as e:
            logger.error(f"Failed to send real-time progress update: {e}")
    
    async def _async_send_progress_update(self, payload: dict):
        """Async send progress update and snapshot"""
        try:
            import redis.asyncio as redis
            import json
            from ..core.config import get_redis_url
            from .progress_snapshot_service import snapshot_service
            
            # Connect to Redis
            redis_client = redis.from_url(get_redis_url(), decode_responses=True)
            
            # Channel name - use normalized function
            from .websocket_gateway_service import WebSocketGatewayService
            channel = WebSocketGatewayService.normalize_channel(self.project_id)
            
            # 1) Save snapshot
            await snapshot_service.save_snapshot(channel, payload)
            
            # 2) Publish message to Redis
            await redis_client.publish(channel, json.dumps(payload, ensure_ascii=False))
            
            # 3) Close Redis connection
            await redis_client.aclose()
            
            logger.debug(f"Progress update published: {channel} - {payload}")
            
        except Exception as e:
            logger.error(f"Failed to async send progress update: {e}")
    
    def _get_step_number(self, step: ProcessingStep) -> int:
        """Get step number"""
        step_number_map = {
            ProcessingStep.STEP1_OUTLINE: 1,
            ProcessingStep.STEP2_TIMELINE: 2,
            ProcessingStep.STEP3_SCORING: 3,
            ProcessingStep.STEP4_TITLE: 4,
            ProcessingStep.STEP5_CLUSTERING: 5,
            ProcessingStep.STEP6_VIDEO: 6
        }
        return step_number_map.get(step, 0)
    
    def _get_step_progress(self, step: ProcessingStep) -> float:
        """Get progress percentage for step"""
        step_progress_map = {
            ProcessingStep.STEP1_OUTLINE: 10,
            ProcessingStep.STEP2_TIMELINE: 30,
            ProcessingStep.STEP3_SCORING: 50,
            ProcessingStep.STEP4_TITLE: 70,
            ProcessingStep.STEP5_CLUSTERING: 85,
            ProcessingStep.STEP6_VIDEO: 95
        }
        return step_progress_map.get(step, 0)
    
    def _save_step_result(self, step: ProcessingStep, result: Any):
        """Save step result to database"""
        # This can save results to appropriate database tables as needed
        # For example, clip results to Clip table, collection results to Collection table
        logger.info(f"Step {step.value} result saved")
    
    def _save_pipeline_results_to_database(self, results: Dict[str, Any]):
        """Save pipeline execution results to database"""
        try:
            logger.info(f"Starting to save pipeline results for project {self.project_id} to database")
            
            # Get project directory
            project_dir = self.adapter.data_dir / "projects" / self.project_id
            
            # Use DataSyncService to sync data to database
            from ..services.data_sync_service import DataSyncService
            sync_service = DataSyncService(self.db)
            
            # Sync project data
            sync_result = sync_service.sync_project_from_filesystem(self.project_id, project_dir)
            
            if sync_result.get("success"):
                logger.info(f"Project {self.project_id} data sync successful: {sync_result}")
            else:
                logger.error(f"Project {self.project_id} data sync failed: {sync_result}")
            
            logger.info(f"All pipeline results for project {self.project_id} saved to database")
            
        except Exception as e:
            logger.error(f"Failed to save pipeline results to database: {e}")
            # Don't raise exception to avoid affecting pipeline completion status
    
    def _validate_step_dependencies(self, steps_to_execute: List[ProcessingStep]):
        """Validate step dependencies"""
        # Define step dependencies
        step_dependencies = {
            ProcessingStep.STEP2_TIMELINE: [ProcessingStep.STEP1_OUTLINE],
            ProcessingStep.STEP3_SCORING: [ProcessingStep.STEP2_TIMELINE],
            ProcessingStep.STEP4_TITLE: [ProcessingStep.STEP3_SCORING],
            ProcessingStep.STEP5_CLUSTERING: [ProcessingStep.STEP4_TITLE],
            ProcessingStep.STEP6_VIDEO: [ProcessingStep.STEP5_CLUSTERING]
        }
        
        # Only check first step's dependencies, other steps will be checked during execution
        if steps_to_execute:
            first_step = steps_to_execute[0]
            if first_step in step_dependencies:
                required_steps = step_dependencies[first_step]
                missing_steps = []
                
                for req_step in required_steps:
                    # Check if dependency step has completed (by checking output file)
                    step_output = self.adapter.get_step_output_path(req_step.value)
                    if not step_output.exists():
                        missing_steps.append(req_step)
                
                if missing_steps:
                    missing_step_names = [step.value for step in missing_steps]
                    raise ValueError(f"Step {first_step.value} missing dependency steps: {missing_step_names}")
    
    def get_pipeline_status(self) -> Dict[str, Any]:
        """Get pipeline status"""
        task = self.task_repo.get_by_id(self.task_id)
        if not task:
            return {"error": "Task does not exist"}
        
        return {
            "task_id": self.task_id,
            "project_id": self.project_id,
            "task_status": task.status.value,
            "task_progress": task.progress,
            "error_message": task.error_message,
            "step_status": self.step_status,
            "step_timings": self.step_timings,
            "created_at": task.created_at.isoformat() if task.created_at else None,
            "updated_at": task.updated_at.isoformat() if task.updated_at else None
        }
    
    def retry_step(self, step: ProcessingStep, **kwargs) -> Dict[str, Any]:
        """Retry a specific step"""
        logger.info(f"Retrying step: {step.value}")
        
        # Clean up step's intermediate files
        self.adapter.cleanup_intermediate_files(step.value)
        
        # Re-execute step
        return self.execute_step(step, **kwargs)
    
    def get_step_result(self, step: ProcessingStep) -> Any:
        """Get step result"""
        return self.adapter.get_step_result(step.value)
    
    def get_step_performance_summary(self) -> Dict[str, Any]:
        """Get step performance summary"""
        if not self.step_timings:
            return {"message": "No performance data available"}
        
        total_time = sum(timing["execution_time"] for timing in self.step_timings.values())
        step_performance = {}
        
        for step_name, timing in self.step_timings.items():
            percentage = (timing["execution_time"] / total_time * 100) if total_time > 0 else 0
            step_performance[step_name] = {
                "execution_time": timing["execution_time"],
                "percentage": percentage,
                "start_time": timing["start_time"],
                "end_time": timing["end_time"]
            }
        
        return {
            "total_execution_time": total_time,
            "step_performance": step_performance,
            "slowest_step": max(self.step_timings.items(), key=lambda x: x[1]["execution_time"])[0] if self.step_timings else None,
            "fastest_step": min(self.step_timings.items(), key=lambda x: x[1]["execution_time"])[0] if self.step_timings else None
        }
    
    def resume_from_step(self, start_step: ProcessingStep, srt_path: Optional[Path] = None) -> Dict[str, Any]:
        """Resume execution from a specific step"""
        logger.info(f"Resuming execution from step {start_step.value}")
        
        # Get all steps starting from the specified step
        all_steps = [
            ProcessingStep.STEP1_OUTLINE,
            ProcessingStep.STEP2_TIMELINE,
            ProcessingStep.STEP3_SCORING,
            ProcessingStep.STEP4_TITLE,
            ProcessingStep.STEP5_CLUSTERING,
            ProcessingStep.STEP6_VIDEO
        ]
        
        try:
            start_index = all_steps.index(start_step)
            
            # Only execute incomplete steps
            steps_to_execute = []
            for step in all_steps[start_index:]:
                step_output = self.adapter.get_step_output_path(step.value)
                if not step_output.exists():
                    steps_to_execute.append(step)
                else:
                    logger.info(f"Step {step.value} already completed, skipping")
            
            if not steps_to_execute:
                logger.info("All steps already completed, no need to execute")
                return {"message": "All steps already completed"}
            
            logger.info(f"Will execute steps: {[step.value for step in steps_to_execute]}")
            
            if start_step == ProcessingStep.STEP1_OUTLINE:
                if not srt_path:
                    raise ValueError("Resuming from Step1 requires SRT file path")
                return self.execute_pipeline(srt_path, steps_to_execute)
            else:
                # Verify prerequisite steps are completed
                for step in all_steps[:start_index]:
                    step_output = self.adapter.get_step_output_path(step.value)
                    if not step_output.exists():
                        raise ValueError(f"Prerequisite step {step.value} not completed, cannot resume from {start_step.value}")
                
                return self.execute_pipeline(Path("dummy.srt"), steps_to_execute)
                
        except ValueError as e:
            logger.error(f"Failed to resume execution: {e}")
            raise
    
    def get_step_status_summary(self) -> Dict[str, Any]:
        """Get step status summary"""
        if not self.step_status:
            return {"message": "No step status data available"}
        
        completed_steps = [step for step, status in self.step_status.items() if status["status"] == "completed"]
        failed_steps = [step for step, status in self.step_status.items() if status["status"] == "failed"]
        running_steps = [step for step, status in self.step_status.items() if status["status"] == "running"]
        
        return {
            "total_steps": len(self.step_status),
            "completed_steps": completed_steps,
            "failed_steps": failed_steps,
            "running_steps": running_steps,
            "completion_rate": len(completed_steps) / len(self.step_status) * 100 if self.step_status else 0,
            "step_details": self.step_status
        }