#!/usr/bin/env python3
"""Export YouTube cookies using CloakBrowser (stealth Chromium)."""

from __future__ import annotations

import argparse
import sys
import time
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))


def cookies_to_netscape(cookies: list[dict]) -> str:
    lines = ["# Netscape HTTP Cookie File", "# Generated by cloak_youtube_cookies.py", ""]
    for cookie in cookies:
        domain = cookie.get("domain", "")
        if domain and not domain.startswith("."):
            domain = f".{domain.lstrip('.')}"
        include_subdomains = "TRUE" if domain.startswith(".") else "FALSE"
        path = cookie.get("path", "/") or "/"
        secure = "TRUE" if cookie.get("secure") else "FALSE"
        expires_raw = cookie.get("expires", 0) or 0
        try:
            expires_int = int(expires_raw)
        except (TypeError, ValueError):
            expires_int = 0
        if expires_int < 0:
            expires_int = 0
        name = cookie.get("name", "")
        value = cookie.get("value", "")
        if not name:
            continue
        lines.append("\t".join([domain, include_subdomains, path, secure, str(expires_int), name, value]))
    return "\n".join(lines) + "\n"


def export_cookies(url: str, output: Path, wait_seconds: float = 8.0) -> int:
    from cloakbrowser import launch

    output.parent.mkdir(parents=True, exist_ok=True)
    browser = launch(headless=True)
    try:
        context = browser.new_context(
            locale="en-US",
            timezone_id="America/New_York",
            user_agent=(
                "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
                "(KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"
            ),
        )
        page = context.new_page()
        print(f"Opening YouTube via CloakBrowser: {url}")
        page.goto("https://www.youtube.com", wait_until="domcontentloaded", timeout=120_000)
        time.sleep(2)
        page.goto(url, wait_until="domcontentloaded", timeout=120_000)
        time.sleep(wait_seconds)

        title = page.title()
        print(f"Page title: {title}")

        cookies = context.cookies()
        youtube_cookies = [
            c for c in cookies
            if "youtube" in c.get("domain", "") or "google" in c.get("domain", "")
        ]
        if not youtube_cookies:
            youtube_cookies = cookies

        output.write_text(cookies_to_netscape(youtube_cookies), encoding="utf-8")
        print(f"Wrote {len(youtube_cookies)} cookies to {output}")
        return len(youtube_cookies)
    finally:
        browser.close()


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("url", help="YouTube video URL")
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        default=PROJECT_ROOT / "data" / "youtube_cookies.txt",
    )
    parser.add_argument("--wait", type=float, default=8.0, help="Seconds to wait on video page")
    args = parser.parse_args()

    count = export_cookies(args.url, args.output, args.wait)
    if count == 0:
        print("No cookies captured", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
